### ISSUE TITLE
fmtstr table problem in rst 

### ISSUE THREAD

**Issue by iromise** [ctf-wiki/ctf-wiki#104]

**Comment by iromise** [comment]
also in heap structure.

**Comment by iromise** [comment]
Basicly fix the bug, but it remains to be fixed better in the future, fix ways:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pandoc-discuss/wGVGKiUhcNU/joMwRyXyBAAJ

**Comment by 40huo** [comment]
== == ==
1     1    1
== == ==
1     1     1
2      2    2
== == ==

这样的表格行不？

**Comment by iromise** [comment]
seems cannot, see it on http://rst.ninjs.org.
