### ISSUE TITLE
https://ctf-wiki.github.io/ctf-wiki/ 站点在调整吗？

### ISSUE THREAD

**Issue by zwhubuntu** [ctf-wiki/ctf-wiki#112]
各位大佬，https://ctf-wiki.github.io/ctf-wiki/ 这个站点正在调整吗？目前无法访问

**Comment by iromise** [comment]
是的，你可以先看markdown分支下对应的内容。

**Comment by 40huo** [comment]
Fixed c68c9247b7d9c1ff87badd9116a161e0d01fadcd

**Comment by zwhubuntu** [comment]
谢谢各位大大
