### ISSUE TITLE
frame faking 中汇编错误

### ISSUE THREAD

**Issue by lifeand** [ctf-wiki/ctf-wiki#144]
https://ctf-wiki.github.io/ctf-wiki/pwn/stackoverflow/others.html 
frame faking 一节中，程序入口点应该为push ebp; mov ebp,esp, leave 相当于mov esp,ebp;pop ebp

**Comment by iromise** [comment]
非常感谢。这里主要做示意说明，没有严格区分AT&T 汇编语法和 Intel 语法。之后会加上去这里的汇编语法是AT&T 语法。

**Comment by iromise** [comment]
已经注明。
