### ISSUE TITLE
换用 mkdocs 进行文档生成

### ISSUE THREAD

**Issue by 40huo** [ctf-wiki/ctf-wiki#213]
综合考虑写作和阅读体验，经一段时间的测试，准备将文档生成从 Sphinx 切换到 MkDocs 上，这样大家就可以直接写 Markdown 了，省去了转换的步骤。
目前考虑使用 mkdocs-material 主题，[测试站点地址](https://40huo.github.io/ctf-wiki/)，只放了部分有代表性的文档。
首页支持切换主题的颜色，字体（正文、代码块）也可以切换。所以在此征求意见，大家可以挑一个自己认为好看的配色和字体回复，如果有其他意见和建议也请一并提出。

**Comment by 40huo** [comment]
目前的配色是主色 white，辅助色 red
正文字体 Monda，代码字体 Fira Mono

**字体是从谷歌字体加载的，所以需要在 fonts.google.com 中有**

**Comment by iromise** [comment]
主色感觉cyan 好看些，，辅助色认不出来是哪里的，，

**Comment by 40huo** [comment]
辅助色是鼠标移到链接上的时候的颜色
