### ISSUE TITLE
Virus Trojan.Gen.2 in examples

### ISSUE THREAD

**Issue by cclauss** [ctf-wiki/ctf-wiki#218]
I did a git clone of this repo and Symantec Endpoint Protection light up like a Christmas tree saying that several of the example files were infected with the Trojan.Gen.2 virus.  Are others seeing the same?

* M	"reverse/examples/unpack\350\204\261\345\243\263\347\257\207/1-\345\215\225\346\255\245\350\267\237\350\270\252\346\263\225.zip"
* M	"reverse/examples/unpack\350\204\261\345\243\263\347\257\207/2-ESP\345\256\232\345\276\213\346\263\225.zip"
* M	"reverse/examples/unpack\350\204\261\345\243\263\347\257\207/3-\344\270\200\346\255\245\345\210\260\350\276\276OEP.zip"
* M	"reverse/examples/unpack\350\204\261\345\243\263\347\257\207/4-\345\206\205\345\255\230\351\225\234\345\203\217\346\263\225.zip"
* D	"reverse/examples/unpack\350\204\261\345\243\263\347\257\207/5-\346\234\200\345\220\216\344\270\200\346\254\241\345\274\202\345\270\270\346\263\225.zip"
* M	"reverse/examples/unpack\350\204\261\345\243\263\347\257\207/6-SFX\346\263\225.zip"

**Comment by iromise** [comment]
so, what is the filename?

**Comment by iromise** [comment]
oh, It may be just ok, as you know in reverse, some packed binay will be seen as virus, actually they are just some binay examples. You can reverse binary in a virtual machine if you want to make sure that you are enough safe.  @Vancir can give you more info.

**Comment by Vancir** [comment]
As iromise  said, I strongly suggest you run these programs in the virtual machine, even though these files themself are not malicious.

**Comment by cclauss** [comment]
modified:   reverse/unpack/example/1_trace.zip
	modified:   reverse/unpack/example/2_esp.zip
	modified:   reverse/unpack/example/3_direct2oep.zip
	modified:   reverse/unpack/example/4_memory.zip
	deleted:    reverse/unpack/example/5_last_exception.zip
	modified:   reverse/unpack/example/6_sfx.zip
	deleted:    reverse/unpack/example/unpack_dll.zip
