### ISSUE TITLE
Support for Python 3 and the use of the six module?

### ISSUE THREAD

**Issue by cclauss** [ctf-wiki/ctf-wiki#220]
Given that Python 2 goes EOL in two years, should we start ensuring compatibility with Python 3 as well as 2?

Does anyone object to the use of the [six](http://six.readthedocs.io/) module to aid in achieving compatibility with both Python 2 and Python 3.

**Comment by iromise** [comment]
Yes, thanks for your mention. We will try to transfer to python3 version in next few month.

**Comment by cclauss** [comment]
No objection to the use of six?

**Comment by iromise** [comment]
Personly, I'd like to just entirely change code to python3 version in this repo. But it depends on the opinion of the member in CTF Wiki Team.
