### ISSUE TITLE
base32编码最多出现"="符号的个数并不止3个，而应该是6个

### ISSUE THREAD

**Issue by JmNkS** [ctf-wiki/ctf-wiki#259]
RT

**Comment by iromise** [comment]
不知是否可以举个例子？对这个不熟悉。如果确认是问题的话，欢迎提个 PR。

**Comment by JmNkS** [comment]
对这个也不熟悉，不过是通过以下网页进行验证的：
http://www.qqxiuzi.cn/bianma/base.php
分别尝试编码“a”、"aa"、"aaa"，观察其中包含"="的数量得出的结论。

该网页内也有对base32的阐述：

由于数据的二进制传输是按照8比特一组进行（即一个字节），因此Base32按5比特切分的二进制数据必须是40比特的倍数（5和8的最小公倍数）。例如输入单字节字符“%”，它对应的二进制值是“100101”，前面补两个0变成“00100101”（二进制值不足8比特的都要在高位加0直到8比特），从左侧开始按照5比特切分成两组：“00100”和“101”，后一组不足5比特，则在末尾填充0直到5比特，变成“00100”和“10100”，这两组二进制数分别转换成十进制数，通过上述表格即可找到其对应的可打印字符“E”和“U”，但是这里只用到两组共10比特，还差30比特达到40比特，按照5比特一组还需6组，则在末尾填充6个“=”。
