### ISSUE TITLE
fastbin处图片有点小问题

### ISSUE THREAD

**Issue by Aryb1n** [ctf-wiki/ctf-wiki#284]
https://ctf-wiki.github.io/ctf-wiki/pwn/heap/fastbin_attack/#_2
末尾的这个这个图片是不是画的稍有问题, main_area指向的应该是chunk3, chunk3指向chunk2, chunk2指向chunk1
![pic](https://ctf-wiki.github.io/ctf-wiki/pwn/heap/figure/fastbin_link_list.png)

**Comment by iromise** [comment]
这个并没有问题，fastbin 是按照 fd 进行链接的，而且每次是插入链表头。这里如果非要说有问题，那就是 chunk2 指向 chunk3 时，应该是 fd 指向。 @vbty 你觉得呢？

**Comment by Aryb1n** [comment]
```c
int main(void)
{
    void *chunk1,*chunk2,*chunk3;
    chunk1=malloc(0x30);
    chunk2=malloc(0x30);
    chunk3=malloc(0x30);
    //进行释放
    free(chunk1);
    free(chunk2);
    free(chunk3);
    return 0;
}
```
打扰大佬了. 
喔, 我的意思是, 对应这段文字里提到的代码, 是不是大佬画图的时候笔误
图中应该是不是main_arena -> chunk3 -> chunk2 -> chunk1 这样

**Comment by iromise** [comment]
我曹，没细看没细看，，不好意思，，我让写这部分的作者修改一下。。 @vbty  真的是有错误。。

**Comment by Aryb1n** [comment]
好的, 大佬们辛苦了O(∩_∩)O~~

**Comment by vbty** [comment]
已修改
