### ISSUE TITLE
RSA_chosen_cipher补充

### ISSUE THREAD

**Issue by Alphavct** [ctf-wiki/ctf-wiki#327]
以下是没学过数论、半天尝试搞懂此题的新手的理解

对向下取整的补充：
N为奇数，N/2会去尾，但是脚本中终止条件是low == up，而不是P被取唯一可能值，所以返回偶数时P<N/2中等号不是必须的。

数学归纳法中的补充：

发送2C时，返回奇数，即2P mod N 为奇数，这表明2P已经超过了N，并且返回的奇数是2P减去 奇数倍N的结果。此时，由于P显然小于N，故2P<2N，所以必定为减去了1个N
发送4C时，返回偶数，即4P mod N 为偶数，这表明4P减去了 偶数倍N。此时考虑2P>N即4P>2N并且4P<4N，故必定为减去了2个N

解释每次发的数值是上一次的两倍的原因以及k与x的关系：

假设发送第i个包(2C,4C,8C...)时，服务器经计算减去了x个N
那么当发送第i+1个包时，
(1)若返回奇数，表明减去了奇数个N，根据上述讨论，至少减去2x个N，小于 2x+2个N，所以一共减去了2x+1个N
(2)若返回偶数，表明减去了偶数个N，根据上述讨论，至少减去2x个N，小于 2x+2个N，所以一共减去了2x个N

发送2C时，即2的一次幂，减去1个N
发送4C时，即2的二次幂，减去了2个N
发送二的x次幂乘以C时，减去k个N，结论：k = 2x + 1 (返回奇)  k = 2x（返回偶）
事实上此处相当于x1,x2,x3......k为某个x的后一项

**Comment by iromise** [comment]
> 终止条件是low == up，而不是P被取唯一可能值

这样的终止条件不就是 P 取唯一值么？

**Comment by Alphavct** [comment]
开区间的问题吧，如果上下界差1，最后low==up是可以的，但是P取不到值了

**Comment by iromise** [comment]
啥，那不就是 low 么，，，最后程序都跑出来了。。

**Comment by Alphavct** [comment]
我的意思就是。。。P并不是靠区间长度为1夹出来的，而是靠上下界相等出来的

**Comment by Alphavct** [comment]
额。。我没写过那脚本，我只看了原理。。。如果答案就是最后的low的话。。。那肯定是没问题了

**Comment by Alphavct** [comment]
由于P存在，所以y=x的思路感觉很巧妙。
不过某个包发过去，减去了x个N的话，包的数值大小乘二后，至少减去2x个N，至多减去2x+1个N，再根据奇偶性取舍也许会更好理解一点。我一开始写的证明太复杂了。。
话说还有就是。。。归纳法第i次时的数学公式解析又失败了。。

**Comment by iromise** [comment]
我根据你的建议进行了一定的修改，，然后公式我也修了下。。。

**Comment by iromise** [comment]
就目前而言，一切都显示正常，我暂时关闭这个 issue 了，有问题可以随时继续交流。
