### ISSUE TITLE
格式化字符串漏洞例子描述问题

### ISSUE THREAD

**Issue by fpbibi** [ctf-wiki/ctf-wiki#351]
https://ctf-wiki.github.io/ctf-wiki/pwn/fmtstr/fmtstr_example/#_22

中的描述有点问题

简单看看程序，发现程序正如名字所描述的，是一个联系人相关的程序，可以实现创建，修改，删除，打印联系人的信息。而再仔细阅读，可以发现在**输入联系人信息**的时候存在格式化字符串漏洞。

应该改为

简单看看程序，发现程序正如名字所描述的，是一个联系人相关的程序，可以实现创建，修改，删除，打印联系人的信息。而再仔细阅读，可以发现在**打印联系人信息**的时候存在格式化字符串漏洞。

**Comment by 0x01f** [comment]
已更正， thanks
