### ISSUE TITLE
关于一个简单题目的更优解法

### ISSUE THREAD

**Issue by shesl-meow** [ctf-wiki/ctf-wiki#369]
关于 古典密码 → 总结 → 2017 SECCON Vigenere3d 的一个更优解法
- 关于此题的分析：

  1. 考虑到在程序正常运行下，数组访问不会越界，我们在讨论时做以下约定：$ arr[index] \Leftrightarrow arr[index \% len(arr)] $

  2. 关于python程序中定义的 `_l` 函数，发现以下等价关系：$ \_l(offset, arr)[index] \Leftrightarrow arr[index + offset] $
  3. 关于python的main函数中三维矩阵t的定义，发现以下等价关系：$ t[a][b][c] \Leftrightarrow \_l(a+b, s)[c] $
  4. 综合第2第3点的观察，有如下等价关系：$ t[a][b][c] \Leftrightarrow s[a+b+c] $
  5. 我们将s视为一种编码格式，即：编码过程s.find(x)，解码过程s[x]。并直接使用其编码结果的数字替代其所代指的字符串，那么加密过程可以用以下公式表示：
     - $ e = f +  k1 +k2 $
     - 其中，e是密文，f是明文，k1与k2是通过复制方法得到、与f长度一样的密钥，**加法是向量加**。

- 所以我们只需要通过计算 `k1+k2` ，模拟密钥，即可解密。关于此题的解密python脚本：

  ```python
  enc_str = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz_{}'
  dec_dic = {k:v for v,k in enumerate(enc_str)}
  encrypt = 'POR4dnyTLHBfwbxAAZhe}}ocZR3Cxcftw9'
  flag_bg = 'SECCON{**************************}'
  
  sim_key = [dec_dic[encrypt[i]]-dec_dic[flag_bg[i]] for i in range(7)] # 破解模拟密钥
  sim_key = sim_key + sim_key[::-1]
  
  flag_ed = [dec_dic[v]-sim_key[k%14] for k,v in enumerate(encrypt)] # 模拟密钥解密
  flag_ed = ''.join([enc_str[i%len(enc_str)] for i in flag_ed]) # 解码
  print(flag_ed)
  ```

**Comment by iromise** [comment]
可以直接提一个 PR？
