### ISSUE TITLE
Python沙箱逃逸：3.6新增的f-string

### ISSUE THREAD

**Issue by Cirn09** [ctf-wiki/ctf-wiki#381]
就像这样：
![image](https://user-images.githubusercontent.com/25722111/45479084-1620b180-b778-11e8-8ffd-3bf4372586f1.png)

详情见 [PEP 498](https://www.python.org/dev/peps/pep-0498/)

**Comment by WinMin** [comment]
好。我晚上看看

**Comment by WinMin** [comment]
i will update  it
