### ISSUE TITLE
pwn花式栈溢出有点没弄懂

### ISSUE THREAD

**Issue by Alphavct** [ctf-wiki/ctf-wiki#382]
栈迁移的over一题，最后一个payload，我想的是回到缓冲区首地址，leave ret先把'22222222'到ebp，然后开始执行pop_rdi_ret，但是payload最后第二个参数stack-0x30，为什么要减掉0x30.......各种试也没打成功......

**Comment by 0x01f** [comment]
@Alphavct 为了满足 `leave; ret` 时的栈结构，[调试](http://docs.pwntools.com/en/stable/gdb.html?highlight=gdb#pwnlib.gdb.attach) 一下会很容易看出来
