### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by WinMin** [ctf-wiki/ctf-wiki#40]
你好~能留个联系方式吗~我们想贡献一部分内容 比如Pwn的堆部分

**Comment by iromise** [comment]
你好，这一部分也正是我也想写的，欢迎加微信讨论，uromise，头像如github头像。

**Comment by iromise** [comment]
@WinMin  我刚刚在 #42 里给出了目前的堆利用的一个简单的想法，可以一同讨论。

**Comment by 40huo** [comment]
@WinMin https://ctf-wiki.bearychat.com
