### ISSUE TITLE
不懂爆破canary所需次数

### ISSUE THREAD

**Issue by Demon-Wang** [ctf-wiki/ctf-wiki#413]
![stack_reading](https://user-images.githubusercontent.com/17793300/46611339-18401b00-cb40-11e8-9448-94bfaa531e34.png)

中级rop章节中：

猜测出canary一个字节之后仍然crash，怎么判断这一个字节正确呢
32位下 
不应该是2^8 * 2^8 * 2^8 * 2^8
为什么是2^8 * 4=1024呢
:)目前还没有看canary的原理，可能是原理不清楚的锅?
上一章花式rop中有一个 leak canary
通过read末尾不加\0实现，为了防止canary最后一位是\0覆盖了最后一个字节
canary的最后一个字节一定是\0吗？

**Comment by Demon-Wang** [comment]
另外 中级rop中 leak 二进制代码的时候
def leak(length, rdi_ret, puts_plt, leak_addr, stop_gadget):
    sh = remote('127.0.0.1', 9999)
    payload = 'a' * length + p64(rdi_ret) + p64(leak_addr) + p64(
        puts_plt) + p64(stop_gadget)
    sh.recvuntil('password?\n')
    sh.sendline(payload)
    try:
        data = sh.recv()
        sh.close()
        try:
            data = data[:data.index("\nWelCome")]
        except Exception:
            data = data
        if data == "":
            data = '\x00'
        return data
    except Exception:
        sh.close()
        return None

这部分代码有什么用呢：
        try:
            data = data[:data.index("\nWelCome")]
        except Exception:
            data = data

为什么只取\nWelCome的内容
\nWelCome前面为什么有一个\n呢
 ‘WelCome my friend,Do you know password?’存于rodata段里面
如果缺少了Welcome，那岂不是leak出来的code 偏移计算会出现问题？

def leak函数每次是重新启动一个进程？ 上一次函数的结果会对之后造成影响还是rev缓冲区残留啥的吗？python学的不好:)

**Comment by iromise** [comment]
关于第一个问题，是否可以描述清楚点，这里面一共有哪些子问题。

关于第二个问题，时间有些长了，我今晚看一下，然后处理一下。

**Comment by adavis10006** [comment]
第一個問題 假設canary有 4 bytes 且因為 seed 沒變的關係導致 canary 永遠一樣的情形下，要爆破 canary 的方法是分 byte 來做的，首先我們先 overload 第一個 byte，當我們爆破的值對了就可以通過canary的驗證，以此類推拿已知的第一個的byte 要爆破的第二個byte和未更動的3, 4 bytes 繼續爆破，所以每個byte 最多需要256次 共 256 * 4 次 
第二個問題 我不是很確定 canary是否一定最低位一定為 0 ， 不過我覺得重要的是知道當你 leak 不出 canary 時要想到可能是因為現在這位(不一定是最低位)是 0

**Comment by iromise** [comment]
> 第一個問題 假設canary有 4 bytes 且因為 seed 沒變的關係導致 canary 永遠一樣的情形下，要爆破 canary 的方法是分 byte 來做的，首先我們先 overload 第一個 byte，當我們爆破的值對了就可以通過canary的驗證，以此類推拿已知的第一個的byte 要爆破的第二個byte和未更動的3, 4 bytes 繼續爆破，所以每個byte 最多需要256次 共 256 * 4 次

是这样的，2^32 次方指的是无脑暴力。

> 第二個問題 我不是很確定 canary是否一定最低位一定為 0 ， 不過我覺得重要的是知道當你 leak 不出 canary 時要想到可能是因為現在這位(不一定是最低位)是 0

Canary 最低字节一定是 0。

**Comment by bash-c** [comment]
@Demon-Wang 第一个问题中的爆破次数的问题， @adavis10006 已经解释的很清楚了

canary 最后一个字节是否一定为 `\0` 的问题，正常情况下是的，原理可以看 [canary](https://ctf-wiki.github.io/ctf-wiki/pwn/linux/mitigation/Canary/)（其他保护的原理我们也会逐渐补充）。

注意我指的正常情况最后一位是 `\0`，某些题目（如 [noxCTF2018-TheBlackCanary](https://ctftime.org/task/6545))中修改了canary生成方法，就不一定是 `\0` 了。

**Comment by MaskRay** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob;hb=5a580643111ef6081be7b4c7bd1997a5447c903f;f=sysdeps/unix/sysv/linux/dl-osinfo.h#l50

stack canary最低字節一定是0。

```c
static inline uintptr_t __attribute__ ((always_inline))
_dl_setup_stack_chk_guard (void *dl_random)
{
  union
  {
    uintptr_t num;
    unsigned char bytes[sizeof (uintptr_t)];
  } ret;

  /* We need in the moment only 8 bytes on 32-bit platforms and 16
     bytes on 64-bit platforms.  Therefore we can use the data
     directly and not use the kernel-provided data to seed a PRNG.  */
  memcpy (ret.bytes, dl_random, sizeof (ret));
#if BYTE_ORDER == LITTLE_ENDIAN
  ret.num &= ~(uintptr_t) 0xff;
#elif BYTE_ORDER == BIG_ENDIAN
  ret.num &= ~((uintptr_t) 0xff << (8 * (sizeof (ret) - 1)));
#else
# error "BYTE_ORDER unknown"
#endif
  return ret.num;
}
```
