### ISSUE TITLE
杂项中的 RAR 压缩包伪加密问题

### ISSUE THREAD

**Issue by li-fstz** [ctf-wiki/ctf-wiki#414]
[RAR 格式 - 伪加密](https://ctf-wiki.github.io/ctf-wiki/misc/archive/rar/#_4)

> RAR 文件的伪加密在文件头中的位标记字段上，用 010 Editor 可以很清楚的看见这一位，修改这一位可以造成伪加密。

只是简单更改位标记上的加密位后会导致文件头 HEAD_CRC 校验失败进而使得压缩包失效，请问能否提供更详细的说明？

我自己查询后找到了关于这个 CRC 的描述：

> The CRC is calculated using the standard polynomial 0xEDB88320. 

但是始终无法手动计算出正常 RAR 文件中一个 HEAD_CRC 的值。

**Comment by WinMin** [comment]
emmm 你可以找下  crc 校验从哪算到哪 。算完之后你接着再更改校验位

**Comment by XuCcc** [comment]
> > emmm 你可以找下 crc 校验从哪算到哪 。算完之后你接着再更改校验位
> 
> 计算不能呀，我手动算出来的对不上

**Comment by XuCcc** [comment]
> > emmm 你可以找下 crc 校验从哪算到哪 。算完之后你接着再更改校验位
> 
> 计算不能呀，我手动算出来的对不上

具体过程可以参考010editor中的[Rar.bt](https://www.sweetscape.com/010editor/repository/templates/file_info.php?file=RAR.bt&type=0&sort=)模板。
```c
	if (HeadType != MARKER)
	{
		local uint16 crcCheck = Checksum(CHECKSUM_CRC32, startof(HeadType), HeaderSize-sizeof(HEAD_CRC)) & 0xFFFF;
		if (crcCheck != HEAD_CRC)
		{
            Warning("Header CRC mismatch in Block #%Lu", iBlocksCounter);
			Printf("Header CRC mismatch in Block #%Lu: expected CRC is 0x%X, got 0x%X\n", iBlocksCounter, crcCheck, HEAD_CRC);
			++iBadCRCCounter;
		}
	}
```

以`Head_TYPE`开始，长度为`HeaderSize-sizeof(HEAD_CRC)`，`HEAD_CRC`两字节，则计算得到的CRC32值只取两个低位字节。

**For example** 计算 Archieve Header的CRC，以红框内的数据计算


![截图](https://user-images.githubusercontent.com/18616776/61921555-1b51ae00-af90-11e9-91b2-3e57b61ec24a.PNG)
