### ISSUE TITLE
Use 'Consolas' or other font as default code block font.

### ISSUE THREAD

**Issue by summershrimp** [ctf-wiki/ctf-wiki#431]
Current font of code is too hard to recognize "&" . Please consider it.

**Comment by 40huo** [comment]
Remote font feature is based on fonts.google.com.
How about "Source Sans Pro" for sans serif and "Souce Code Pro" for monospace?

**Comment by summershrimp** [comment]
Any other font other than "Fira Mono" would be great for me. "@" and "&" is way too different from common font. Maybe consider open a vote for whether change the font or not ?

**Comment by iromise** [comment]
@40huo , I think it is better to change some font as "@" and "&"  are really strange...

**Comment by 40huo** [comment]
change mono font to source code pro
