### ISSUE TITLE
请教basic_rop中的一个疑问

### ISSUE THREAD

**Issue by soulway-weng** [ctf-wiki/ctf-wiki#457]
你好，我想请教一下:
路径/docs/pwn/linux/stackoverflow/basic_rop中的ret2libc3一题中
![image](https://user-images.githubusercontent.com/29256541/48944944-95461900-ef63-11e8-8216-af73259f0287.png)

变量s的栈开始位置为[ebp - 64h]，也就是100个字节的大小，加上old ebp应该是104个字节的大小
那为什么在第一次溢出的时候填了112个‘A’呢?
![image](https://user-images.githubusercontent.com/29256541/48945109-20271380-ef64-11e8-8cd3-80c7390e73cf.png)
那如果真是112个'A'的话，为什么在第二次溢出的时候又填回了104个'A'呢?
![image](https://user-images.githubusercontent.com/29256541/48945219-814ee700-ef64-11e8-82b1-ff0a3b2fa3fe.png)

**Comment by iromise** [comment]
好像是有问题，你可以尝试运行一下么？不过我记得我当时都是正常可以打的 exp。
