### ISSUE TITLE
请教一个Chunk Extend and Overlapping中的问题

### ISSUE THREAD

**Issue by Demon-Wang** [ctf-wiki/ctf-wiki#459]
原文:
基本示例 2：对 inuse 的 smallbin 进行 extend中

释放后，chunk1 把 chunk2 的内容吞并掉并一起置入 unsorted bin

0x602000:   0x0000000000000000  0x00000000000000b1 <=== 被放入unsorted bin
0x602010:   0x00007ffff7dd1b78  0x00007ffff7dd1b78
0x602020:   0x0000000000000000  0x0000000000000000
0x602030:   0x0000000000000000  0x0000000000000000
0x602040:   0x0000000000000000  0x0000000000000000
0x602050:   0x0000000000000000  0x0000000000000000
0x602060:   0x0000000000000000  0x0000000000000000
0x602070:   0x0000000000000000  0x0000000000000000
0x602080:   0x0000000000000000  0x0000000000000000
0x602090:   0x0000000000000000  0x0000000000000021
0x6020a0:   0x0000000000000000  0x0000000000000000
0x6020b0:   0x00000000000000b0  0x0000000000000020 <=== 注意此处标记为空
0x6020c0:   0x0000000000000000  0x0000000000000000
0x6020d0:   0x0000000000000000  0x0000000000020f31 <=== top chunk
有疑惑。
前面的章节中 深入理解堆的实现 free的实现部分，对所有chunk的释放，不管是否合并，不管是不是fastbin(当然fastbin不合并)都会将原chunk的内容格式化:即执行free_perturb(chunk2mem(p), size - 2 * SIZE_SZ);

从后一个chunk标记pre_inuse标记为空可以看出该段是释放后的内存情况了

修改unsortbin的size是在free之前，为什么extend之后的 被overlap的chunk内容没有被清0呢
即0x602098部分。。。

难道是free_perturb内部函数实现问题？

可能是我深入理解堆没看明白吗？感谢大佬们回答:）

**Comment by iromise** [comment]
你需要仔细理解 free_perturb 函数的功能，他做的并不是清零的操作

```c

/* ------------------ Testing support ----------------------------------*/
 
static int perturb_byte;


static void free_perturb (char *p, size_t n)
{
if (__glibc_unlikely (perturb_byte))
memset (p, perturb_byte, n);
}
```
默认情况下，是不会执行 `memset` 函数的。

**Comment by Demon-Wang** [comment]
> 你需要仔细理解 free_perturb 函数的功能，他做的并不是清零的操作
> 
> ```c
> /* ------------------ Testing support ----------------------------------*/
>  
> static int perturb_byte;
> 
> 
> static void free_perturb (char *p, size_t n)
> {
> if (__glibc_unlikely (perturb_byte))
> memset (p, perturb_byte, n);
> }
> ```
> 
> 默认情况下，是不会执行 `memset` 函数的。

嗯 大概看了搜索了一下likely系列的函数，发现是用来做编译器代码优化的(减少跳转)
所以在perturb默认为0的时候 if语句是不会执行的，也就是说在malloc和free的时候都没有对申请或施放的chunk内容进行格式化，除了bk和fd需要处理的情况下。

谢谢:)
