### ISSUE TITLE
Contributor Bug

### ISSUE THREAD

**Issue by iromise** [ctf-wiki/ctf-wiki#481]
The contributor is not as the readme shows...

**Comment by Escapingbug** [comment]
Is this helpful?
https://help.github.com/enterprise/2.8/user/articles/why-are-my-contributions-not-showing-up-on-my-profile/#you-havent-added-your-local-git-commit-email-to-your-profile

**Comment by iromise** [comment]
No, it is because of the plugin(opencollective) we use. It does not work well.

**Comment by 40huo** [comment]
slack notification test

**Comment by FantasqueX** [comment]
Hi, there! I found a project called contributors-img which provides the same service as open collective, and it is easy to use. Here is an [example](https://contrib.rocks/preview?repo=ctf-wiki%2Fctf-wiki). Also, I'll make a pull request and link this issue.

**Comment by arttnba3** [comment]
Hi all,

This issue was fixed in #779 , as I've merge @FantasqueX 's pull request. As `opencollective` could not provide a correct result compared to `contributors-img`, I think it's necessary to make a change.

Best regards,
arttnba3
CTF-wiki team
04/10/2024
