### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by onlykood** [ctf-wiki/ctf-wiki#500]
PWN -> Linux Pwn -> 安全防护机制 -> canary

原文：
如果抑或的结果为 0，说明 canary 未被修改，函数会正常返回，这个操作即为检测是否发生栈溢出。

应该修改为：
如果异或的结果为 0，说明 canary 未被修改，函数会正常返回，这个操作即为检测是否发生栈溢出。

**Comment by iromise** [comment]
欢迎提交 PR，Pull Request。
