### ISSUE TITLE
png.md不存在

### ISSUE THREAD

**Issue by Nicolana** [ctf-wiki/ctf-wiki#553]
png.md 不存在

**Comment by bash-c** [comment]
具体是哪个链接呢。。。

**Comment by Nicolana** [comment]
https://ctf-wiki.github.io/ctf-wiki/misc/picture/png-zh/png.md

在 [png-zh.md](https://ctf-wiki.github.io/ctf-wiki/misc/picture/png-zh/) 里面的EN | ZH  ， 选择 EN时候会打开上面的链接。

顺便说一句， 中文版没有了目录， 看起来有点不方便，如果不麻烦建议加上。谢谢

**Comment by Nicolana** [comment]
中文目录

**Comment by bash-c** [comment]
中文目录的问题已经在修改了 #554 ，刚刚转换到双语的版本，问题比较多，之后会逐一改过来的

**Comment by WinMin** [comment]
@40huo 你来看看？

**Comment by Nicolana** [comment]
![flag](https://user-images.githubusercontent.com/20972473/59823591-3ca3f680-9361-11e9-988e-35fcc46c1773.jpg)

不知道可不可以增加个这个音频题的隐写技巧介绍呢？ 好难做啊， 我还没做出来

**Comment by 40huo** [comment]
这个是变成双语导致的链接不对吧
https://ctf-wiki.github.io/ctf-wiki/misc/picture/png-zh/
这里是正常的，EN下404
