### ISSUE TITLE
中文界面没有目录啦

### ISSUE THREAD

**Issue by S-Ex1t** [ctf-wiki/ctf-wiki#554]

**Comment by 23R3F** [comment]
是啊，点击zh后，目录就不见鸟

**Comment by iromise** [comment]
@mahaloz  it seems there is no outline after clicking the zh button.

**Comment by mahaloz** [comment]
What section in what folder? /docs?

**Comment by iromise** [comment]
All docs, take https://ctf-wiki.github.io/ctf-wiki/ as an example, after clicking the ZH button, we can not see the table of contents.

**Comment by mahaloz** [comment]
Ah I see. The Mkdocs are using the English version which makes table of contents unavailable. I think the way we could remedy this is by using the old mkdocs combined with the new one.

**Comment by mahaloz** [comment]
The mkdocs needs the old paths merged with this new one with the new ‘name-zh.md’ as the other paths

**Comment by mahaloz** [comment]
I’m on a 5 hour flight starting now, I can fix it after (about 6 hours from now. If desperately needed revert or use google translated TOC)

**Comment by iromise** [comment]
OK. Waiting for your good news.

**Comment by mahaloz** [comment]
Decided to buy internet on the flight. Working on a fix now.

**Comment by mahaloz** [comment]
Fix not possible without some refactoring of the entire Mkdocs layout
