### ISSUE TITLE
web/sql injection常用工具 链接失效

### ISSUE THREAD

**Issue by h3h3da** [ctf-wiki/ctf-wiki#572]
如题，此处的burp和sqlmap的连接不能访问，应该是站点 http://static.hx99.net/ 挂了吧，请及时更新。
![屏幕快照 2019-07-26 下午3 39 03](https://user-images.githubusercontent.com/20582659/61935103-5e297b00-afbc-11e9-8348-221256862644.png)

**Comment by AngelKitty** [comment]
@40huo 参考文献前四个好像也是失效的 
![屏幕快照 2019-07-27 下午7 53 56](https://user-images.githubusercontent.com/30405643/61994104-d8cfc480-b0a8-11e9-9d15-1e407befdaff.png)

**Comment by 40huo** [comment]
> @40huo 参考文献前四个好像也是失效的
> ![屏幕快照 2019-07-27 下午7 53 56](https://user-images.githubusercontent.com/30405643/61994104-d8cfc480-b0a8-11e9-9d15-1e407befdaff.png)

done
