### ISSUE TITLE
Syntax Error: x = gmpy math.sqrt(delta)

### ISSUE THREAD

**Issue by cclauss** [ctf-wiki/ctf-wiki#59]
https://github.com/ctf-wiki/ctf-wiki/blob/master/crypto/asymmetric/rsa/example/sctf-rsa1/level2/wiener.py#L73

flake8 testing of https://github.com/ctf-wiki/ctf-wiki on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./crypto/asymmetric/rsa/example/sctf-rsa1/level2/wiener.py:73:29: E999 SyntaxError: invalid syntax
                x = gmpy math.sqrt(delta)
                            ^
```

**Comment by iromise** [comment]
I am so sorry, initially, I plan to use this script( https://github.com/radx64/rsa-wiener-attack/blob/master/main.py ) to solve the wiener problem. Afterly, I use this script( https://github.com/pablocelayes/rsa-wiener-attack ). But I have no idea why this script looks like that.... So I just delete it... Sorry for making you confused.
