### ISSUE TITLE
hidden number problem描述问题

### ISSUE THREAD

**Issue by xhyumiracle** [ctf-wiki/ctf-wiki#595]
[hidden number problem](https://github.com/ctf-wiki/ctf-wiki/blob/master/docs/crypto/asymmetric/lattice/cvp.md)中，
`which is approximately $1$ most significant digits of $x \mod p$.`
$1$貌似应该是$l$

**Comment by AngelKitty** [comment]
> [hidden number problem](https://github.com/ctf-wiki/ctf-wiki/blob/master/docs/crypto/asymmetric/lattice/cvp.md)中，
> `which is approximately $1$ most significant digits of $x \mod p$.`
> $1$貌似应该是$l$

应该是笔误了
