### ISSUE TITLE
竞赛时间表 && rank 的相关建议

### ISSUE THREAD

**Issue by AngelKitty** [ctf-wiki/ctf-wiki#615]
来自一些师傅的提议，希望增加比赛时间表，学习ctftime，显示一些即将到来的比赛啥的，这样也可以让更多的ctfer参与到比赛中，共同进步！！！

**Comment by AngelKitty** [comment]
ref：https://ctftime.org/

**Comment by AngelKitty** [comment]
以及添加ctfrank相关的建议

**Comment by 40huo** [comment]
ctfrank不是已经有了么

**Comment by iromise** [comment]
我感觉可以从以下角度出发考虑一下
1. 我们现在应该主要任务是丰富内容，这个比赛表可以从ctf time 和 xctf 上获取。
2. ctf rank 已经有对应的网站。
3. 如果有人愿意帮忙搞，自然是不错的。

**Comment by WinMin** [comment]
我觉得没必要 ctf-wiki 没必要搞 竞赛时间表。

**Comment by 40huo** [comment]
> 我觉得没必要 ctf-wiki 没必要搞 竞赛时间表。

你们的ctfrank好像不怎么更新了啊

**Comment by WinMin** [comment]
@40huo 因为在准备更新2.0 开发咕了
