### ISSUE TITLE
编译成pdf版本。

### ISSUE THREAD

**Issue by yckyos261** [ctf-wiki/ctf-wiki#631]

**Comment by WinMin** [comment]
需要PDF版本的ctf-wiki?

**Comment by yckyos261** [comment]
> 需要PDF版本的ctf-wiki?

我今天试着编译了一下，不成体系。有些没网、不能用自己电脑的环境下其实是需要pdf的。

**Comment by iromise** [comment]
@yckyos261 
你可以自己本地 clone 下来，然后直接 build 好就行了。readme 有相关介绍。

**Comment by snow212-cn** [comment]
> @yckyos261
> 你可以自己本地 clone 下来，然后直接 build 好就行了。readme 有相关介绍。

不能编译成单文件，很不方便拷贝，也不能传到平板、手机上浏览

**Comment by iromise** [comment]
@snow212-cn 目前没有做成单文件的计划。如果你有需求，欢迎 PR。
