### ISSUE TITLE
勘误 格式化字符串漏洞例子-堆上的格式化字符串漏洞一节

### ISSUE THREAD

**Issue by fdgnneig** [ctf-wiki/ctf-wiki#654]
该节介绍例子2015 年 CSAW 中的 contacts时，以下论述存在错误

原文中
"其次，我们可以确定栈上存储格式化字符串的地址 0xffffcd2c 相对于格式化字符串的偏移为 6，得到这个是为了构造我们的联系人。
再者，我们可以看出下面的地址保存着上层函数的调用地址，其相对于格式化字符串的偏移为 11，这样我们可以直接修改上层函数存储的 ebp 的值。"
栈上存储格式化字符串的地址 0xffffcd2c 相对于格式化字符串的偏移应该为11，
而栈中保存着上层函数的调用地址的ebp，其相对于格式化字符串的偏移应该为6，
文中将上述两者颠倒了

**Comment by 18328052728** [comment]
原文为“其次，我们可以确定栈上存储格式化字符串的地址 0xffffcd2c 相对于格式化字符串的偏移为 6，得到这个是为了构造我们的联系人。
再者，我们可以看出下面的地址保存着上层函数的调用地址，其相对于格式化字符串的偏移为 11，这样我们可以直接修改上层函数存储的 ebp 的值。”

**Comment by AngelKitty** [comment]
@18328052728 能直接提交pr吗？非常感谢！

**Comment by 18328052728** [comment]
好的~

**Comment by 18328052728** [comment]
https://wiki.x10sec.org/pwn/fmtstr/fmtstr_example/#_22
以上网页中显示的内容与项目中对应文档的的内容不一致，网页中现实的内容是错误的，但是项目文档中是正确的。。。

**Comment by 18328052728** [comment]
@AngelKitty

**Comment by AngelKitty** [comment]
@18328052728 您应该参考本仓库的web pages，详见：https://ctf-wiki.github.io/ctf-wiki/pwn/linux/fmtstr/fmtstr_example-zh/#_22

您所给的这个link可能是该网站管理者早期fork本仓库的内容，以前存在的一些错误都有在后期的issue和pr中得到了及时的反馈与修复，所以建议您参考本仓库的web pages，一旦仓库内容有更新，web pages会有一个实时的内容调整。

所以建议您查看CTF-Wiki相关内容的话，建议查看本仓库的链接：https://ctf-wiki.github.io/ctf-wiki/

非常感谢您的反馈！！！
