### ISSUE TITLE
请问slack链接是失效了吗

### ISSUE THREAD

**Issue by chrisyang2003** [ctf-wiki/ctf-wiki#667]

**Comment by iromise** [comment]
似乎没有？这个可以么？ https://join.slack.com/t/ctf-wiki/shared_invite/enQtNTkwNDg5NDUzNzAzLTQ3YTliNzI5OGNhM2NmNzI3NTU0YWRlNWFkY2EzYTExN2Y3ZjRkNzYzYmRhNDNlYmY5YTVmNjNhYjliZDgyNTY

**Comment by chrisyang2003** [comment]
好的,已经加入了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Baozheng Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午2:12
收件人:&nbsp;"ctf-wiki/ctf-wiki"<ctf-wiki@noreply.github.com&gt;;
抄送:&nbsp;"咖喱羊羊羊"<1017975501@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ctf-wiki/ctf-wiki] 请问slack链接是失效了吗 (#667)





 
似乎没有？这个可以么？ https://join.slack.com/t/ctf-wiki/shared_invite/enQtNTkwNDg5NDUzNzAzLTQ3YTliNzI5OGNhM2NmNzI3NTU0YWRlNWFkY2EzYTExN2Y3ZjRkNzYzYmRhNDNlYmY5YTVmNjNhYjliZDgyNTY
