### ISSUE TITLE
Unwanted typora-root-url header in Markdown files

### ISSUE THREAD

**Issue by yechs** [ctf-wiki/ctf-wiki#673]
## Motivation

While reading through the docs, I found out that there is a unwanted header at top of the doc

![image](https://user-images.githubusercontent.com/49149993/79588698-e2053380-8106-11ea-95c8-d95dc051b396.png)

## Problem

It seems that some of the editors are using Typora and included this configuration in `*.md` files, which then rendered into headers at the beginning of docs.

https://github.com/ctf-wiki/ctf-wiki/blob/c5c2f529a3ad88c79b283b17315c2b9491890519/docs/introduction/mode-zh.md#L2-L4

I did a [quick search on GitHub](https://github.com/ctf-wiki/ctf-wiki/search?q=typora-root-url&unscoped_q=typora-root-url) and found out about 20+ more `typora-root-url` entries.

## Solution

I might be able to open a PR to remove all `typora-root-url` entries, if that's welcomed (?)

**Comment by AngelKitty** [comment]
@yechs I will be very appreciated if you can help me.
