### ISSUE TITLE
PWN堆溢出

### ISSUE THREAD

**Issue by ClarkCh** [ctf-wiki/ctf-wiki#738]
pwn - linux pwn - glibc heap利用 - 堆溢出， 原文：
"
注意用户区域的大小不等于 chunk_hear.size，chunk_hear.size = 用户区域大小 + 2 * 字长
"

这里说的chunk_hear.size应该是指malloc_chunk结构体大小吧？chunk_hear这个名词不知道哪里来的

**Comment by WinMin** [comment]
#762 

已经修正 感谢提交 issue
