### ISSUE TITLE
页面搜索框无响应

### ISSUE THREAD

**Issue by 1094093288** [ctf-wiki/ctf-wiki#745]
无论中英文 键入关键词 直接无响应，需关闭页面重新打开，每次必触发！
![750](https://user-images.githubusercontent.com/41280135/109245081-cc7a9300-781a-11eb-9e33-4bad0dc928bc.png)

**Comment by iromise** [comment]
我好像没有遇到这个问题，我看您这个版本是旧版的 wiki。您可以试下 `https://ctf-wiki.org`。

**Comment by 1094093288** [comment]
您发的链接搜索框为何出不来结果？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ctf-wiki/ctf-wiki"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 晚上11:00
收件人:&nbsp;"ctf-wiki/ctf-wiki"<ctf-wiki@noreply.github.com&gt;;
抄送:&nbsp;"一梦不醒╮(oo)♪"<1094093288@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ctf-wiki/ctf-wiki] 页面搜索框无响应 (#745)





 
我好像没有遇到这个问题，我看您这个版本是旧版的 wiki。您可以试下 https://ctf-wiki.org。

**Comment by iromise** [comment]
![image](https://user-images.githubusercontent.com/11772027/109387894-c8479600-793e-11eb-91c6-7a8dd6f6bca8.png)
@1094093288

**Comment by 1094093288** [comment]
问题解决了，谢谢
