### ISSUE TITLE
能否在学习资源中添加CTFHub

### ISSUE THREAD

**Issue by yw9381** [ctf-wiki/ctf-wiki#760]
RT
https://www.ctfhub.com/
CTFHub拥有对新手最友好的学习技能树
有各种各样的历年出现过的真题
有专门收集各种WP聚合的站点 [https://writeup.ctfhub.com/](https://writeup.ctfhub.com/)

**Comment by WinMin** [comment]
> RT
> https://www.ctfhub.com/
> CTFHub拥有对新手最友好的学习技能树
> 有各种各样的历年出现过的真题
> 有专门收集各种WP聚合的站点 https://writeup.ctfhub.com/

我觉得应该没什么大问题 @iromise 

你甚至可以提个 PR  ，

**Comment by iromise** [comment]
@yw9381 肯定没问题啊，你可以直接提个 PR。

**Comment by WinMin** [comment]
已经  merge

#764
