### ISSUE TITLE
关于Misc章节--编码分析--计算机相关的编码--小小内容问题

### ISSUE THREAD

**Issue by Neptune1729** [ctf-wiki/ctf-wiki#776]
![image](https://user-images.githubusercontent.com/68886715/114271564-90a33200-9a44-11eb-8484-fb7c00bddf1d.png)
字符**0** 对应的 ascii码 应为48

**Comment by Neptune1729** [comment]
附上连接：https://ctf-wiki.org/misc/encode/computer/

**Comment by Neptune1729** [comment]
> @Neptune1729 Thanks, 可以提一个 PR 么？

Sure,已提PR(第一次提PR，如有错误，还望海涵)

**Comment by iromise** [comment]
#777 Merged.
