### ISSUE TITLE
关于linux栈溢出fancy-rop.md的babypie这一节的建议

### ISSUE THREAD

**Issue by zhangdg** [ctf-wiki/ctf-wiki#786]
原文是：
可以发现, 此时的返回地址与 get shell 函数的地址只有低位的 16 bit 不同, 如果覆写低 16 bit 为 0x?A3E, 就有一定的几率 get shell

事实上，此时的返回地址与get shell函数只有低8 bit不同，所以只需要写低8 bit为0x3E就可以get shell了，exp.py也不需要用循环去碰运气。可惜我的环境上执行system('/bin/sh')之后总是跑死，不知道什么原因。

**Comment by bash-c** [comment]
@zhangdg 感谢指出这一问题，刚才又看了一下题目，`最低位的16 bit不同` 的说法有误，是只有最低8 bit不同，欢迎提一个pr修改此处。
至于`system("/bin/sh")` crash的问题，推测是因为在执行system函数时栈地址需要按照0x10的粒度对齐，你可以尝试一下把最低8 bit改为0x3f（跳过一个push指令调整栈）

**Comment by WinMin** [comment]
#https://github.com/ctf-wiki/ctf-wiki/commit/69888b97a0fe1626e6650cf424394474fda60e08

已经修改, 关闭 issue
