### ISSUE TITLE
pwn/linux/kernel/environment给的ctf-tools失效

### ISSUE THREAD

**Issue by Golbeze** [ctf-wiki/ctf-wiki#791]
点开之后404

**Comment by iromise** [comment]
@Golbeze 不好意思，CTF Tools 最近缺乏维护，对应的链接为：https://ctf-wiki.github.io/ctf-tools/binary-core-tools/virtualization/qemu/qemu-introduction/。这个链接也可以通过原有的链接来推测出来。
