### ISSUE TITLE
关于加密章节数学公式爆炸的问题

### ISSUE THREAD

**Issue by jingyuexing** [ctf-wiki/ctf-wiki#793]
![图片](https://user-images.githubusercontent.com/19589872/124345296-b0449380-dc0a-11eb-87c5-84c117b49ff9.png)
都成这样了

**Comment by jingyuexing** [comment]
![图片](https://user-images.githubusercontent.com/19589872/124345314-d1a57f80-dc0a-11eb-9795-59dfc5c588fb.png)
也许是页面的这个未能正确加载导致的？

**Comment by FantasqueX** [comment]
![image](https://user-images.githubusercontent.com/46747123/124345503-d3237780-dc0b-11eb-98a1-a8cf34ad85c1.png)
这边显示是正常的，也许是网络问题？

**Comment by jingyuexing** [comment]
那就是网络问题了
