### ISSUE TITLE
关于花式栈溢出 fancy-rop.md 中 stack smash 的问题

### ISSUE THREAD

**Issue by Arachnid-27** [ctf-wiki/ctf-wiki#809]
glibc-2.31 开始不打印 argv[0] 了，所以会拿不到 flag
https://elixir.bootlin.com/glibc/glibc-2.31/source/debug/fortify_fail.c

**Comment by iromise** [comment]
@Arachnid-27 非常感谢，可以提一个 PR 么？

**Comment by WinMin** [comment]
新增说明 https://github.com/ctf-wiki/ctf-wiki/commit/3d4906eba154b7bb886c1b3682dcc04b9f5b8b03
