### ISSUE TITLE
中级rop到高级rop都没有二进制题目文件

### ISSUE THREAD

**Issue by hatface** [ctf-wiki/ctf-wiki#814]
从[中级rop](https://ctf-wiki.org/pwn/linux/user-mode/stackoverflow/x86/medium-rop/)到[高级rop](https://ctf-wiki.org/pwn/linux/user-mode/stackoverflow/x86/advanced-rop/ret2dlresolve/)都没有题目的二进制文件，希望解决下

**Comment by WinMin** [comment]
简单 review 了下, 大概还差
ret2csu里的, 2016 华山杯 SU_PWN
partial overflow 里的 2018-XNUCA-gets

应该还差这俩文件没有补充, 回头我找到就传上来, 这里先关闭 issue 了
