### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by Wen-Tao-Zhang** [ctf-wiki/ctf-wiki#821]
[位置](https://github.com/ctf-wiki/ctf-wiki/blob/20347aa69de094236c7a27f18c22b76bab69cdeb/docs/zh/docs/reverse/identify-encode-encryption/introduction.md?plain=1#L65) 

image number -> [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming))?

**Comment by iromise** [comment]
@Wen-Tao-Zhang 是的，可能不同的人叫法不太一样，叫 magic number 更规范一些。欢迎 PR~
