### ISSUE TITLE
Uninitialized Storage Pointer数组部分存在问题

### ISSUE THREAD

**Issue by bcYng-w** [ctf-wiki/ctf-wiki#833]
数组处“然后我们调用 attack 函数，传入的 _value 值为 2，可以从交易中发现 a 被传入的 _value 值覆盖了：”这句话有问题，a的值不是因为被_value覆盖，而是读取a的值作为了数组长度，然后再push导致数组长度+1，再将a覆盖为数组长度。
所以调用attack时不管_value为几，调用之后a都会变成a+1.
![image](https://user-images.githubusercontent.com/92173296/162581010-84b036d5-eca3-4220-a2a5-243312dd17d8.png)

**Comment by hitcxy** [comment]
> 数组处“然后我们调用 attack 函数，传入的 _value 值为 2，可以从交易中发现 a 被传入的 _value 值覆盖了：”这句话有问题，a的值不是因为被_value覆盖，而是读取a的值作为了数组长度，然后再push导致数组长度+1，再将a覆盖为数组长度。 所以调用attack时不管_value为几，调用之后a都会变成a+1. ![image](https://user-images.githubusercontent.com/92173296/162581010-84b036d5-eca3-4220-a2a5-243312dd17d8.png)

对的，确实是之前的师傅写的有问题，我马上订正
