### ISSUE TITLE
gif.md在官网上仍存在markdown渲染错误问题

### ISSUE THREAD

**Issue by yixinBC** [ctf-wiki/ctf-wiki#845]
官网：https://ctf-wiki.org/misc/picture/gif/#_3
此问题在https://github.com/ctf-wiki/ctf-wiki/issues/225 中已有描述，然而似乎并未修复。

**Comment by iromise** [comment]
Thanks♪(･ω･)ﾉ，能麻烦您提一个 PR 来修复下么？

**Comment by yixinBC** [comment]
但是我去查看了GitHub仓库中的源文件，并没有发现markdown错误，甚至在GitHub上渲染出来的markdown预览并不存在此问题

**Comment by iromise** [comment]
可能是 mkdocs 渲染不支持下面的 SourceCode解析吧
