### ISSUE TITLE
基本ROP中的例子ret2shellode二进制文件bss段不可执行，和例子中描述的不符。

### ISSUE THREAD

**Issue by slatbox** [ctf-wiki/ctf-wiki#846]
基本ROP中的例子ret2shellode二进制文件中bss段不可执行，和教程给出的描述不符，给出的exp无法通过。

**Comment by WinMin** [comment]
> 基本ROP中的例子ret2shellode二进制文件中bss段不可执行，和教程给出的描述不符，给出的exp无法通过。

#830  看这个
