### ISSUE TITLE
SROP 内容纰漏

### ISSUE THREAD

**Issue by zsNick** [ctf-wiki/ctf-wiki#852]
在SROP技术中 讲得非常详细  但是有一点内容有所纰漏

signal 机制第3点:
signal handler 返回后，内核为执行 sigreturn 系统调用，为该进程恢复之前保存的上下文，其中包括将所有压入的寄存器，重新 pop 回对应的寄存器，最后恢复进程的执行。其中，32 位的 sigreturn 的调用号为 77，64 位的系统调用号为 15。

这里 32位的sigreturn调用号应该是0x77(119) , 64 位的系统调用号为 15(0xf)
还请完善下 

内容参考 
https://www.slideshare.net/AngelBoy1/sigreturn-ori 
PPT第11页

**Comment by WinMin** [comment]
> 在SROP技术中 讲得非常详细 但是有一点内容有所纰漏
> 
> signal 机制第3点: signal handler 返回后，内核为执行 sigreturn 系统调用，为该进程恢复之前保存的上下文，其中包括将所有压入的寄存器，重新 pop 回对应的寄存器，最后恢复进程的执行。其中，32 位的 sigreturn 的调用号为 77，64 位的系统调用号为 15。
> 
> 这里 32位的sigreturn调用号应该是0x77(119) , 64 位的系统调用号为 15(0xf) 还请完善下
> 
> 内容参考 https://www.slideshare.net/AngelBoy1/sigreturn-ori PPT第11页


感谢， 已经修正： [fix](https://github.com/ctf-wiki/ctf-wiki/commit/fe16a89f7f7d4c24c5280b5361e9d6be4591f984)
