### ISSUE TITLE
关于Pwn中Format String章节里的一些问题。

### ISSUE THREAD

**Issue by windf411** [ctf-wiki/ctf-wiki#880]
1.在“利用”中的“泄露任意地址内存 ”这个知识点中，后面的例子不知道在讲“printf”还是“scanf”的利用，比较混乱。

**Comment by WinMin** [comment]
> 1.在“利用”中的“泄露任意地址内存 ”这个知识点中，后面的例子不知道在讲“printf”还是“scanf”的利用，比较混乱。

我速览了一下, 后面这个例子应该是在讲如何通过 `printf` 的格式化字符串漏洞来 leak 出 scanf 的 libc 地址

**Comment by windf411** [comment]
> > 1.在“利用”中的“泄露任意地址内存 ”这个知识点中，后面的例子不知道在讲“printf”还是“scanf”的利用，比较混乱。
> 
> 我速览了一下, 后面这个例子应该是在讲如何通过 `printf` 的格式化字符串漏洞来 leak 出 scanf 的 libc 地址

谢谢，我又仔细看了一下，是我理解错了。
