### ISSUE TITLE
扩展维纳攻击 三个小解密指数的情况 向量B写错了？

### ISSUE THREAD

**Issue by buptsad** [ctf-wiki/ctf-wiki#889]
[https://ctf-wiki.org/crypto/asymmetric/rsa/d_attacks/rsa_extending_wiener/#_5](https://ctf-wiki.org/crypto/asymmetric/rsa/d_attacks/rsa_extending_wiener/#_5)

似乎三个小解密指数的情况的向量B写错了，B与L相乘的结果中第六七八列与W1G23，W2G13，W1W2W3不一致。B的d大概是轮换对称的，文中的d也不对称

**Comment by buptsad** [comment]
呃呃，似乎论文也是这么写的？

**Comment by n-WN** [comment]
> 呃呃，似乎论文也是这么写的？

大胆一点，也许是论文错了（
