### ISSUE TITLE
Kali 执行 source 虚拟环境目录/activate/bin 时报错

### ISSUE THREAD

**Issue by cherriemm** [ctf-wiki/ctf-wiki#909]
Kali 执行 source 虚拟环境目录/activate/bin 时报错

└─$ source ~/.bashrc
Command 'shopt' not found, did you mean:
command 'shout' from deb libshout-tools
Try: sudo apt install
Command 'shopt' not found, did you mean:
command 'shout' from deb libshout-tools
Try: sudo apt install
Command 'shopt' not found, did you mean:
command 'shout' from deb libshout-tools
Try: sudo apt install
Command 'shopt' not found, did you mean:
command 'shout' from deb libshout-tools
Try: sudo apt install
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
/usr/share/bash-completion/bash_completion:1590: parse error near |'
原因：当前终端的默认 shell 不是 Bash，而可能是 Zsh 或其他 shell，而你的 .bashrc 文件中包含了一些特定于 Bash 的命令，比如 shopt 和 complete。
使用 echo $SHELL 查看当前使用的 shel
如果你确实使用的是 Zsh，那么在 .zshrc 中添加你的 source venv目录/bin/activate 命令即可。

**Comment by arttnba3** [comment]
你好 cherriemm，请问能否提供更加详细和规范的报错信息，并检查你的命令是否执行正确？目前我看你在该 issue 中提交的报错信息中所显示的你所执行的命令为 `source ~/.bashrc` ，与 issue 标题的命令似乎不符；其次 Kali Linux 默认的 Shell 似乎是 ZSH 而非 BASH，你似乎应当使用 `.zshrc` 而非 `.bashrc` ？
